### PR TITLE
Feature: Strongly Typed Model Methods

### PR DESCRIPTION
**Pull request by GuyGooL5**
### Summary:
I added a support to strongly type the methods of a given model. 
`ModelType` now supports another generic called `TMethods` which extends a new type `MethodsType` which is an object of string keys and `FunctionType` values.
`TMethods` has a default value of `MethodsType` making it optional, and prevents breaking changes.

#### Types Declarations
```ts
// assume there's a PokemonItem document type

interface PokemonMethods extends MethodsType {
  getNextEvolutions: (pokemonId: string) => Promise<PokemonItem[]>;
}
```
#### Model Definition
```ts
const PokemonModel = dynamoose.model<PokemonItem, PokemonMethods>("Pokemon", PokemonSchema);
```
#### Method implementation
```ts

// the name and the function type will be inferred from the possible entries in PokemonMethods 

PokemonModel.methods.set(
  "getNextEvolutions",
  function (this: typeof PokemonModel, pokemonId: string) {
    //... implement method here
  }
);

// or without 'this' inference (notice that pokemonId should get it's type inferred.
PokemonModel.methods.set("getNextEvolutions", function (pokemonId) {
  //... implement method here
});
```
#### Usage
```ts
PokemonModel.getNextEvolutions("123").then((items) => {
  items.forEach((item) => {
    console.log("possible next evolution:", item);
  });
});
```
### Other information:
Future work will include forcing the methods type on set  and delete methods of model.

### Type (select 1):
- [ ] Bug fix
- [x] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [ ] Test added to report bug (GitHub issue #---- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [X] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [ ] Yes
- [X] No

### Are all the tests currently passing on this PR? (select 1):
- [ ] Yes
- [ ] No
- [X] Not tested yet

### Other:
- [X] I have read through and followed the Contributing Guidelines
- [X] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [X] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/main/LICENSE)
- [X] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [X] I have filled out all fields above

### CODE REVIEW

**Review by fishcharlie — CHANGES_REQUESTED** [review]
We need documentation updates and tests for this.

**Comment by bros4president** [comment]
This would be a very good feature. Right now both Model and Document share the same type, if provided, so you have to keep in mind what in that type is a class method and what is an instance method.

**Comment by GuyGooL5** [comment]
@fishcharlie hi, I'd like to continue working on this feature, and extend it to support item method types as well, yet the codebase is a little 'overwhelming' I'd say 😅. Is there a methodology this project uses to implement new features or someplace to discuss?

**Comment by fishcharlie** [comment]
@GuyGooL5 Thanks! I'm sorry the codebase is overwhelming.

I'd say probably the easiest thing would be to direct message me on Slack with questions you have. You can find the Slack link in the README of the project.

I'd be more than happy to explain any part of the codebase or answer any questions you have about it.

**Pull request closed without merging**
