### PR TITLE
dynamoose#1014 Added modelType and modelTypeFieldName.

### PR DESCRIPTION
**Pull request by abraxas**
### Summary:

This is a partial improvement for #1014 

This PR adds optional `modelType` and `modelTypeFieldName` setting in schemas.  If there are more than 1 schema in a model, this field can be used similar to a mongoose discriminator to "encourage" the model to choose the schema that matches the row's type. 

#### Schema
```
const BaseSchema = dynamoose.schema({
  dataId: {
    type: String,
    hashKey: true,
  },
  type: String
});

const OrderSchema = dynamoose.schema({
  ...BaseSchema,
}, {
  modelType: 'order'
});

const CustomerSchema = dynamoose.schema({
  ...BaseSchema,
}, {
  modelType: 'customer',
});
```

#### Model

```
const DataModel = dynamoose.model('table_name',[OrderSchema,CustomerSchema]);
```

#### General

```
const orderSchema = await DataModel.schemaForObject({ ...otherData, type: 'order'});
const customerSchema = await DataModel.schemaForObject({ ...otherData, type: 'customer'});
```

### GitHub linked issue:
#1014 

### Other information:

By design, this should not slow down any workflows that do not use this, and should insignificantly affect the speed of workflows that do.

### Type (select 1):
- [ ] Bug fix
- [X] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement
- [ ] Test added to report bug (GitHub issue #--- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [X] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [X] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [X] Yes
- [ ] No

### Other:
- [X] I have read through and followed the Contributing Guidelines
- [X] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [X] I have updated the Dynamoose documentation (if required) given the changes I made
- [X] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [X] I have ensured the following commands are successful from the root of the project directory
  - [X] `npm test`
  - [X] `npm run lint`
- [X] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/master/LICENSE)
- [X] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [X] I have filled out all fields above

### CODE REVIEW

**Comment by abraxas** [comment]
I am ok with this to merge if/when it passes review.

I've been using this heavily in my production app (linked to my own repo obviously) and it works well.

**Comment by abraxas** [comment]
Hey @fishcharlie .  I know you're busy, but just checking in about this.  Do you need anything from me to help expedite the merge?  It's been sitting a month now, and I'm just confirmed it'll get stale or conflict with newer/older PRs.

**Comment by fishcharlie** [comment]
@abraxas Apologizes in the delay in getting around to this. Few things that stand out to me:

1. I don't think we need to add those property settings to the schemas. If I remember our conversation and prior research correctly, I think we should be able to do all of this without requiring additional input from the user or API consumer.
2. Is there more that you want to implement here? You mentioned this is a `partial improvement`. What else needs to be done here?

I'll do my best to prioritize this PR better. Again, sorry for the delay in getting around to it.

**Comment by abraxas** [comment]
@fishcharlie 

For 1... nope.  We really needed to add some sort of discriminator.  The alternative we had discussed was to do some validation handwaving so we could pick schema based upon validation failures, but as you pointed out, that could be an incredible waste of cpu cycles... Which even if it were built, should only ever be used when you cannot differentiate by schema any other way.  I *had* planned to just use a validation on a field called "type", but that's really inefficient compared to this solution.  And honestly, this solution is a bit more mongoose-like.

For 2... I don't intend to do more with this change.  I called it a partial fix because I do intend to make other changes to #1014 unrelated to this change.  There's a lot of TS-related oddities in dynamoose even without multiple schemas, but they become more obvious when a developer has to pass around casts to multiple classes.  I think what I have left is potentially much bigger.

Importantly for bullet-point 2, this PR doesn't _introduce_ any odd behaviors whatsoever.  But those behaviors are easier to manage if you're only using one schema per model, which is easy to do if you don't have a feature like this.

**Comment by fishcharlie** [comment]
Discussed this in Slack. Leaning toward a solution where we have a constant type in Dynamoose, where the type must equal a certain value. This would likely be used for strings & numbers. Keeping this PR open as a reminder tho. Will work on implementing and looking into this more when I can find the time.

**Comment by fishcharlie** [comment]
@abraxas We discussed in Slack having a new constant type that would allow for similar behavior. I was just able to implement this. Any chance you could review & test the PR #1089 and let me know what you think?

**Comment by abraxas** [comment]
Hey @fishcharlie .  I'll take a look ASAP.  I'm not on the computer that much right now due to the holiday.  Thanks!

**Comment by fishcharlie** [comment]
@abraxas No problem! I've had free time this holiday so trying to get things solid for Dynamoose. Just take a look at it when you get a chance. Thanks!!

**Comment by fishcharlie** [comment]
Closing as #1089 achieves the same goal as this PR.

**Pull request closed without merging**
