### PR TITLE
Fix "Index can't be found for query." error for a query without an index

### PR DESCRIPTION
**Pull request by daria-garkusha**
### Summary:

Query with a hash key condition and a filter expression without an index should not fail with "Index can't be found for query." error message because it's a valid query in DynamoDB. 
Automatic detection of an index is a nice feature, but it should not limit the functionality of DynamoDB. So a check for an index should be removed or as another possible solution, there should be a setting to disable this behavior.

#### Model
```
const ExampleModel = dynamoose.model(
  "example", {
    "id": {
      "hashKey": true,
      "type": Number,
    },
    "name": {
      "type": String,
    },
   ...   
  });
```

#### General
```
// Should not fail
const response = await ExampleModel.query("id").eq(111).filter("name").eq("Charlie").exec()
```

### Type (select 1):
- [x] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [ ] Test added to report bug (GitHub issue #--- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [x] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [ ] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [ ] Yes
- [x] No

### Other:
- [x] I have read through and followed the Contributing Guidelines
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [ ] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [ ] I have ensured the following commands are successful from the root of the project directory
  - [ ] `npm test`
  - [ ] `npm run lint`
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/master/LICENSE)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

### CODE REVIEW

**Review by fishcharlie — CHANGES_REQUESTED** [review]
CI failures

**Comment by fishcharlie** [comment]
@daria-garkusha Did this work on v2.7.3 but is failing only on v2.8.0? This looks similar to #1243.

**Comment by fishcharlie** [comment]
@daria-garkusha Got it. I wonder why that PR passed the tests then. It's weird that this is working in v2.7.3 but not in v2.8.0. I agree it has something to do with that PR that you linked likely. Just not sure why the tests didn't fail on that one but are failing with this fix.

Haven't had time to dig in a lot tho.

Would like to hear from @andrewda about this tho.

**Comment by daria-garkusha** [comment]
@fishcharlie Tests fail in this PR because as a fix I removed `throw new CustomError.InvalidParameter("Index can't be found for query.");` [here](https://github.com/dynamoose/dynamoose/blob/master/lib/DocumentRetriever.ts#L171) and there is no check for a missing index now. I think those failing tests could be removed as it's probably not possible to determine if an index is really missing or a user would like to execute a query without an index. [find_best_index](https://github.com/dynamoose/dynamoose/blob/master/lib/DocumentRetriever.ts#L169) will still recommend a suitable index if it's not explicitly specified in a query but will be not so strict

**Comment by fishcharlie** [comment]
@daria-garkusha 

> I think those failing tests could be removed as it's probably not possible to determine if an index is really missing or a user would like to execute a query without an index

That makes sense to me, however, I'm unsure why those tests didn't cause problems before.

---

Obviously this is a regression. And in my opinion a pretty major one. So here are my goals ranked by priority right now:

1. Get this bug fixed and get back to v2.7.3 behavior (that was working correctly).
2. Add test cases for this bug so that we don't run into this problem again.
3. Release v2.8.1 version
4. Get #1222 working again, without breaking the test created in step 2.

I saw you added a test to this PR. I'm curious what the result is, if we branched off of v2.7.3, and added in that test. Would that help to prevent this issue and #1243 in the future? And satisfy the step 2 requirement?

If so, I think the solution is to revert #1222. Add in that test, then have @andrewda redo #1222 while ensuring that it passes that test.

I'm **highly** concerned about regression at this point. I don't like the idea at this point of removing those failing tests. I'd like to get back to a clean working state, add tests to prevent this issue in the future, then work forward from there.

**Comment by andrewda** [comment]
Thanks for bringing this up, I'm looking into this further right now.

**Comment by andrewda** [comment]
> This line of [code](https://github.com/dynamoose/dynamoose/blob/master/lib/utils/can_use_index_of_table.ts?rgh-link-date=2021-08-18T15%3A21%3A44Z#L14) will return `true` if there is a hash key and no range key in a query.

I believe this is the correct behavior. If the hash key is the only key in the query, the table index can be used.

> But then [find_best_index](https://github.com/dynamoose/dynamoose/blob/master/lib/DocumentRetriever.ts?rgh-link-date=2021-08-18T15%3A21%3A44Z#L169) will not be able to find an index, which is not required for such query

We are checking the following:

```ts
if (!utils.can_use_index_of_table(this.internalSettings.model.getHashKey(), this.internalSettings.model.getRangeKey(), comparisonChart))
```

So if `can_use_index_of_table` returns `true`, then the `find_best_index` code and accompanying `InvalidParameter` throw will not be run. Removing the throw is a temporary work-around, but will lead to more query errors when an index actually can't be found by Dynamoose.

---

One thing that could certainly cause this is if the `comparisonChart` includes filters, but I believe that would have been an issue before #1222 as well. The only way I can see the following query throwing "Index can't be found for query" is if the filter is included in `comparisonChart` (since otherwise that part of the code should be skipped).

```ts
const response = await ExampleModel.query("id").eq(111).filter("name").eq("Charlie").exec()
```

I'm going to do some more testing around this, but if that really is the issue it should be a pretty straight-forward fix.

**Comment by fishcharlie** [comment]
@andrewda Thanks for your investigation so far. Tagging @markelrod due to #1243.

**Comment by daria-garkusha** [comment]
To be honest, reverting [#1222 ](https://github.com/dynamoose/dynamoose/pull/1222) would be also not the best option because it fixes another issue with a local secondary index... And queries, which are in failing tests, should actually fail not because an index is missing, but because they don't contain a hash key (for the table or an index). Can we maybe check it additionally and raise an error in such a case? It will fix failing tests and at the same time will fulfill the test, which I added

**Comment by fishcharlie** [comment]
@daria-garkusha I'm not saying that it won't be fixed ever. I'm just saying that bug has existed for a long time. Handling regressions is the **top** priority currently. So even if it means reverting a bug fix to solve a regression, I'm **all** for that.

**Comment by andrewda** [comment]
Looks like `filter`s are being included in the chart:

```ts
const response = await ExampleModel.query("id").eq(111).filter("name").eq("Charlie").exec()

// comparisonChart = { id: { type: 'EQ' }, name: { type: 'EQ' } }
```

Additionally, I just tested on v2.7.3 and the test still does not pass, so the issue is present even before #1222.

Working on a fix now, and will put up a PR when I find something.

**Comment by daria-garkusha** [comment]
@fishcharlie I understand that it will be also fixed later. I was just considering if it's possible somehow to keep that fix and solve a current problem. But from the priority, I fully agree that regression has a top priority and should be fixed as soon as possible

**Comment by fishcharlie** [comment]
@daria-garkusha Yeah I'm not opposed to it being fully fixed all at once. However, I also want to limit risk. v2.8.0 has been one of the releases with highest regression for Dynamoose that I can remember in a while. Which isn't good. Just want to reduce the risk of breaking people's integrations.

We'll see what @andrewda is able to find. Thanks for your work on this @andrewda!!

**Comment by andrewda** [comment]
@fishcharlie @daria-garkusha I've put up https://github.com/dynamoose/dynamoose/pull/1244 with a potential fix. I've copied over the test you added in this PR and it is passing.

**Comment by fishcharlie** [comment]
Superseded by #1244

**Pull request closed without merging**
