### PR TITLE
Remove esModuleInterop and fix all the imports

### PR DESCRIPTION
**Pull request by hardyscc**
#### Schema
```
// Code here
```

#### Model
```
// Code here
```

#### General
```
// Code here
```

### GitHub linked issue:

#---

### Type (select 1):
- [ ] Bug fix
- [x] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [ ] Test added to report bug (GitHub issue #--- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [x] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [x] Yes
- [ ] No

### Other:
- [ ] I have read through and followed the Contributing Guidelines
- [ ] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [ ] I have updated the Dynamoose documentation (if required) given the changes I made
- [ ] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I have ensured the following commands are successful from the root of the project directory
  - [x] `npm test`
  - [x] `npm run lint`
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/master/LICENSE)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

### CODE REVIEW

**Comment by fishcharlie** [comment]
image

**PLEASE** GitHub, build a code coverage solution that actually works...

**Comment by hardyscc** [comment]
@fishcharlie  I always use `jest --coverage` it is very good

**Comment by fishcharlie** [comment]
@hardyscc Yeah our solution works well. It's just CodeCov and Coveralls aren't very good. It's not really the code coverage system, it's the reporting to a service that is awful.

**Comment by MickL** [comment]
Maybe use travisci or circleci instead?

**Comment by fishcharlie** [comment]
@MickL Travis CI and Circle CI are both CI platforms. They don't have any tools for reporting code coverage. GitHub Actions I've found to be great. I just hope GitHub expands it to support reporting code coverage in the future.

**Comment by MickL** [comment]
What do you mean by reporting code coverage? They integrate into Github exactly line it is now.

**Comment by fishcharlie** [comment]
> What do you mean by reporting code coverage? They integrate into Github exactly line it is now.

@MickL Take a look at [CodeCov](https://codecov.io) or [Coveralls](https://coveralls.io). I don't know how to explain it beyond that. They provide things like coverage badges (seen on README), commenting on PRs with the change in code coverage for a PR, etc. GitHub doesn't have code coverage integration. They have ways to run code coverage. But no specific features around it.

**Comment by fishcharlie** [comment]
@MickL Wanna review this PR when you get a chance?

**Comment by MickL** [comment]
Idk I have never seen imports like this: `import aws = require("./aws");`. Why not either `import { timeout } from "./timeout";` or `import * as timeout from "./timeout";`?

**Comment by MickL** [comment]
But also I dont get your exports. E.g.:

```
const main = ...
export main
```

Why not `export const main = ...`

Also I see exports that have no name at all? E.g. equals.ts...

**Comment by hardyscc** [comment]
@MickL this is old CommonJS module import, @fishcharlie need that in order to use back his Javascript testcase

**Pull request merged**
