### PR TITLE
Fix local secondary indices being created as HASH keys

### PR DESCRIPTION
**Pull request by sturcotte06**
### Summary:
This fixes an issue I've had with local secondary indices:
```
(node:523) UnhandledPromiseRejectionWarning: ValidationException: Local secondary indices must have a range key
```
Caused by the Schema translation generating this AWS create table query:
```
{
  IndexName: 'attrLocalIndex',
  KeySchema: [{ AttributeName: 'attr', KeyType: 'HASH' }],
  Projection: { ProjectionType: 'ALL' }
}
```
instead of:
```
{
  IndexName: 'attrLocalIndex',
  KeySchema: [{ AttributeName: 'attr', KeyType: 'RANGE' }, { AttributeName: 'id', KeyType: 'HASH' }],
  Projection: { ProjectionType: 'ALL' }
}
```

### Type (select 1):
- [X] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [ ] Test added to report bug (GitHub issue #--- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [X] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [X] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [X] Yes
- [ ] No

### Other:
- [ ] I have read through and followed the Contributing Guidelines
- [ ] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [ ] I have updated the Dynamoose documentation (if required) given the changes I made
- [X] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [X] I have ensured the following commands are successful from the root of the project directory
  - [ ] `npm test`
  - [ ] `npm run lint`
- [X] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/master/LICENSE)
- [X] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [ ] I have filled out all fields above

### CODE REVIEW

**Comment by dolsem** [comment]
Thanks for working on this! Could you please add a quick test that tries to create an LSI and verifies that the resulting request matches the expectation?

**Comment by sturcotte06** [comment]
> Thanks for working on this! Could you please add a quick test that tries to create an LSI and verifies that the resulting request matches the expectation?

I think I've modified the test cases that test table creation parameters with GSI/LSI. I'm not too comfortable with the test infrastructure of the project yet and I'd prefer to keep it minimal for now. If it's a requirement for this PR, could you post a snippet of such a test so I don't lose too much time trying to figure out the details (there's no tests for `getIndexes` right now)?

**Comment by dolsem** [comment]
Hey, sorry for the delay. On second thought, looks like your modified cases are more than sufficient. Thanks again!

**Comment by fishcharlie** [comment]
Merging since all checks pass and since @dolsem approved. Did not test myself.

**Pull request merged**
