### PR TITLE
Update import statement

### PR DESCRIPTION
**Pull request by yyaskriloff**
I'm not sure if I'm correct here. Still, I kept getting the error  "Cannot read properties of undefined (reading 'ddb')" when running dynamoose.aws.ddb.local() to be consistent with the following page in the documentation I would only be able to run this method if I imported the default export. (I'm running on Node 18.14.0)

#### Schema
```
// Code here
```

#### Model
```
// Code here
```

#### General
```
// Code here
```

### GitHub linked issue:

#----

### Type (select 1):
- [ ] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [ ] Test added to report bug (GitHub issue #---- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [ ] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [ ] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [ ] Yes
- [ ] No

### Other:
- [ ] I have read through and followed the Contributing Guidelines
- [ ] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [ ] I have updated the Dynamoose documentation (if required) given the changes I made
- [ ] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [ ] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/main/LICENSE)
- [ ] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [ ] I have filled out all fields above

### CODE REVIEW

**Comment by fishcharlie** [comment]
@yyaskriloff Thanks for this! Are you using TypeScript or Node.js modules? Can you tell me more about your environment setup?

I also need you to agree to the CLA before this can move forward at all.

**Comment by yyaskriloff** [comment]
I was running node v18 I believe.

**Comment by yyaskriloff** [comment]
I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

**Comment by fishcharlie** [comment]
@yyaskriloff And were you using TypeScript or Node.js modules? Or something like that?

**Comment by fishcharlie** [comment]
Closing in favor of eeef084687e26152ebc9aed89dda69199b494dc1

**Pull request closed without merging**
