### PR TITLE
move '@aws-sdk' modules from 'dependencies' to 'peerDependencies'

### PR DESCRIPTION
**Pull request by KanghoonYi**
### Summary:
I moved '@aws-sdk/client-dynamodb', '@aws-sdk/util-dynamodb' to peerDependecies.
On AWS Lambda, '@aws-sdk/*' modules is already embedded([Reference](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)).
Even though i exclude that, when i installed 'dynamoose', '@aws-sdk/client-dynamodb' is included to bundled package.

### Type (select 1):
- [ ] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [ ] Test added to report bug (GitHub issue #---- @---)
- [x] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [x] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have read through and followed the Contributing Guidelines
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/main/LICENSE)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

### CODE REVIEW

**Comment by KanghoonYi** [comment]
I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

**Comment by fishcharlie** [comment]
@KanghoonYi Thanks for this. I agree this is something we need to consider. However, I question if this is a breaking change or not. In npm versions prior to v7 there was a few versions that did not automatically install peerDependencies. Which requires an extra install step. Pretty sure since Dynamoose supports Node.js >= v12, there are a few npm versions we have to think about.

I'm not opposed to doing this. But it feels like a breaking change to me if users are running those older versions of Node.js.

What do you think?

**Comment by KanghoonYi** [comment]
@fishcharlie 
I see...
You are right. This is breaking change.
How about use 'engines' property on package.json?
```json
{
   "engines": {
     "npm": ">= 7.0.0"
   }
}
```
If npm version lower than 7, users get error that require 'npm' upgrade.
NPM upgrade("npm install -g npm@7") is possible on node 12.
[Reference](https://github.com/pixohq/babystory-data-model/pull/15)

> @KanghoonYi Thanks for this. I agree this is something we need to consider. However, I question if this is a breaking change or not. In npm versions prior to v7 there was a few versions that did not automatically install peerDependencies. Which requires an extra install step. Pretty sure since Dynamoose supports Node.js >= v12, there are a few npm versions we have to think about.
> 
> I'm not opposed to doing this. But it feels like a breaking change to me if users are running those older versions of Node.js.
> 
> What do you think?

**Comment by fishcharlie** [comment]
Not a bad idea. I think that'd still be a breaking change tho.

**Pull request closed without merging**
