### PR TITLE
Add tableName option when defining new Model

### PR DESCRIPTION
**Pull request by famence**
### Summary:
Extends `Model` constructor's third arg `options` of type `TableOptionsOptional` with a new type `ModelTableOptions` including new option `tableName` to overwrite the default table name that is equals to a model name (first arg).
Final table name will respect all the prefixes and suffixes since they may be specified by global defaults.

The main goal of this feature is to make it possible to store multiple models within single table.

#### Model
```
const customTableName = "pets";

const Cat = dynamoose.model("Cat", {"id": String}, {"tableName": customTableName})
const Dog = dynamoose.model("Dog", {"id": String}, {"tableName": customTableName})

// Cat.table().name === Dog.table().name  === customTableName // "pets"
```
```
const customTableName = "pets";
const prefix = "my-";

const Cat = dynamoose.model("Cat", {"id": String}, {"tableName": customTableName, "prefix": prefix})

// Cat.table().name === `${prefix}${customTableName}` // "my-pets"
```

### Type (select 1):
- [ ] Bug fix
- [x] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [x] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have read through and followed the Contributing Guidelines
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/main/LICENSE)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

### CODE REVIEW

**Comment by famence** [comment]
I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

**Comment by famence** [comment]
recheck

**Review by fishcharlie — CHANGES_REQUESTED** [review]
Let's add a test to the type tests as well to ensure we are covering the TypeScript typings side of things. Other than that, this looks great! Thanks for the contribution.

**Comment by famence** [comment]
Check the latest commit please — is that what you mean?

**Comment by fishcharlie** [comment]
@famence Yes. Perfect. Looks like our code coverage dropped tho. Can you create another standard unit test to cover that case?

**Comment by famence** [comment]
Just done it already) It is about Table.modelForObject from https://github.com/dynamoose/dynamoose/pull/1516

**Review by fishcharlie — APPROVED** [review]

**Pull request merged**
