### PR TITLE
throughput was not optional

### PR DESCRIPTION
**Pull request by MickL**

### CODE REVIEW

**Comment by MickL** [comment]
There seems to be an error. I tried to fix that but I dont get the code. @fishcharlie Maybe you can take a look?

**Comment by hardyscc** [comment]
@fishcharlie @MickL On the DynamoDB side, we only need to set once `BillingMode: PAY_PER_REQUEST` on the table level, all the subsequent secondary indexes will be auto inherited, therefore better make it optional.

so 
```
	throughput: number | {read: number; write: number};
```
should be
```
	throughput?: "ON_DEMAND" | number | {read: number; write: number};
```
I am happy to help on this PR, if you guys agree with it.

**Comment by fishcharlie** [comment]
> @fishcharlie @MickL On the DynamoDB side, we only need to set once `BillingMode: PAY_PER_REQUEST` on the table level, all the subsequent secondary indexes will be auto inherited, therefore better make it optional.
> 
> so
> 
> ```
> 	throughput: number | {read: number; write: number};
> ```
> 
> should be
> 
> ```
> 	throughput?: "ON_DEMAND" | number | {read: number; write: number};
> ```
> 
> I am happy to help on this PR, if you guys agree with it.

At first glance. This sounds right. Would love to see a PR. Thanks @hardyscc!!

**Comment by hardyscc** [comment]
@MickL please refer to #853

**Comment by MickL** [comment]
Closed in favor of #853

**Pull request closed without merging**
