### PR TITLE
Fixed the duplication of alias property inside guide/schema (Documentation)

### PR DESCRIPTION
**Pull request by sulemanelahi**
I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

@fishcharlie Can please review this PR and fix this typo mistake.

### CODE REVIEW

**Comment by sulemanelahi** [comment]
I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

**Comment by sulemanelahi** [comment]
> @sulemanelahi wave I really appreciate your contribution!
> 
> You have to post the CLI comment in a comment after the github-actions bot comments. You can see [#1503 (comment)](https://github.com/dynamoose/dynamoose/pull/1503#issuecomment-1236368067) as an example of how I did it.
> 
> I'm not sure what this PR is for tho? Where is the duplication?

on dynamoose docs under the [guide/schema section ](https://dynamoosejs.com/guide/Schema#alias-string--string) 

the description of **alias** and **aliases** are same and it doesn't make any sense that why we have three different attribute settings (map/alias/aliases) for implementing same thing.
I thought that it's a typo mistake let me know is it the typo mistake or not.

**Comment by fishcharlie** [comment]
Nope. All three are valid:

https://github.com/dynamoose/dynamoose/blob/e6dadc6baa107e6633eb7691924d6c5d22173ca6/packages/dynamoose/lib/Schema.ts#L711-L788

**Comment by sulemanelahi** [comment]
are these three properties are just for semantic purposes I don't see any difference in terms of the description of it.

**Pull request closed without merging**
