### PR TITLE
Adjust the return of save/create to conform to schema

### PR DESCRIPTION
**Pull request by halan**
### Summary:

This PR adjusts the return of `save` or `create` when the return is `item`. Before my PR the return was exactly what is being sending to the DynamoDB (the result of `toDynamo`). My PR performs a `conformToSchema` on that return and copies the result to `this`'s attributes.

#### Schema
```ts
new dynamoose.Schema({ id: { type: String, hashKey: true }, birthday: Date })
```

#### General
```ts
const birthday = new Date();
const user = await User.create({ birthday });

user.birthday === birthday; // before that PR user.birthday was number
```

### GitHub linked issue:

[#1479](https://github.com/dynamoose/dynamoose/issues/1479)

### Type (select 1):
- [x] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [x] Test added to report bug (GitHub issue [#1479](https://github.com/dynamoose/dynamoose/issues/1479))
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [x] 🚨 YES 🚨
- [ ] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have read through and followed the Contributing Guidelines
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/main/LICENSE)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

### CODE REVIEW

**Comment by famence** [comment]
Hello!
I wonder when can it be merged? I suggest you to switch a target branch to the next minor release if it is correct.
I checked your branch — it works correct.
It also passed all the test on my local machine.

So can you please restart the tests and do the following to satisfy the requirement of CLA (https://github.com/dynamoose/dynamoose/pull/1514#issuecomment-1244526064):

> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/dynamoose/dynamoose/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

Im looking forward for this features to be released :)

**Comment by hpinheiro-godaddy** [comment]
I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

**Comment by hpinheiro-godaddy** [comment]
recheck

**Comment by hpinheiro-godaddy** [comment]
Hey @famence, thanks for the tip. Talking with @fishcharlie we agreed that this is a public interface change, I'm not sure if it's a minor, but IMO it can break some current implementations (that expect timestamp as an integer for example).

I'm also wondering to use it on my code.

**Comment by fishcharlie** [comment]
@hpinheiro-godaddy Looks like you submitted this PR from @halan. I'm assuming both are your accounts. I think for the CLA to work, you need to comment that from your @halan account.

**Comment by halan** [comment]
I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

**Comment by halan** [comment]
recheck

**Comment by halan** [comment]
The failing spec is a race condition.

**Comment by halan** [comment]
@fishcharlie let me know if that approach it's ok.

**Comment by fishcharlie** [comment]
@halan I'm **so** sorry for the delay on this. It's on my radar, I've just been super busy lately. I'll try to review as soon as I can.

@andrewda if you have time before me and want to take a look at this, that'd be great! No pressure tho.

**Comment by jimmyn** [comment]
@fishcharlie could you please have a look at this PR, this is still an issue in the latest version

**Pull request closed without merging**
